[project]
name = "sun-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "cealexop2003", email = "cealexop@ece.auth.gr" }
]
requires-python = ">=3.12"
dependencies = [
    "astral==2.2",
    "gymnasium>=0.28",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "stable-baselines3>=2.3",
    "tensorboard>=2.20.0",
    "torch>=2.9.0",
]

[project.scripts]
sun-tracking = "sun_tracking.rl.train:main"

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"
